import { User } from './users';

export const data = (): User[] => {
  return [
    {
      username: 'lucassiqz',
      completeName: 'Lucas Siqueira',
      description: 'Software Engineer',
      place: 'Brasilia-DF',
      birth: '14 de julho de 1997',
      following: [{ username: 'guilherme-aguiar' }, { username: 'thiagoo' }],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'guilherme-aguiar',
      completeName: 'Guilherme Aguiar',
      description: 'Software Engineer',
      place: 'Brasilia-DF',
      following: [{ username: 'caiooliv' }, { username: 'carlinhos' }],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'caiooliv',
      completeName: 'Caio Oliveira',
      description: 'Software Engineer',
      place: 'Brasilia-DF',
      birth: '18 de janeiro de 1997',
      following: [{ username: 'guilherme-aguiar' }, { username: 'alex' }],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'carlinhos',
      description: 'Software Engineer',
      place: 'Rio de Janeiro-RJ',
      completeName: 'Carlos Eduardo',
      following: [{ username: 'matheus-rn' }],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'matheus-rn',
      completeName: 'Matheus Rabelo Nonato',
      description: 'Software Engineer',
      place: 'Brasilia-DF',
      following: [],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'thiagoo',
      completeName: 'Thiago Assis',
      description: 'Software Engineer',
      place: 'São Paulo-SP',
      following: [{ username: 'we11' }],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'we11',
      description: 'Software Engineer',
      place: 'Rio de Janeiro-RJ',
      completeName: 'Wellington Santiago',
      following: [{ username: 'an@_maria' }, { username: 'mario' }],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'an@_maria',
      description: 'Software Engineer',
      place: 'Curitiba-PR',
      completeName: 'Ana Maria da Silva',
      following: [{ username: 'alex' }],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'mario',
      description: 'Software Engineer',
      place: 'Curitiba-PR',
      completeName: 'Mario Ferreira',
      following: [],
      visited: false,
      pre: 0,
      post: 0,
    },
    {
      username: 'alex',
      description: 'Software Engineer',
      place: 'Curitiba-PR',
      completeName: 'Alex Oliveira',
      following: [{ username: 'lucassiqz' }],
      visited: false,
      pre: 0,
      post: 0,
    },
  ];
};
